### ISSUE TITLE
完美解决v2rayU与easyconnect冲突问题

### ISSUE THREAD

**Issue by yinTang** [fraee/vmess-domain-coverter#2]
但是有个小问题， 加上这两句就完美了

import ssl
ssl._create_default_https_context = ssl._create_unverified_context

其实也不需要服务器啥的，就Mac 每次开机执行一下脚本就好了
#!/bash/bin
python3 v2ray-links.py 
python3 -m http.server 8000

**Comment by fraee** [comment]
👍 感谢提醒，虽然没遇到SSL证书不可信的问题，加上还是保险的。

ps. 我的Mac都是不关机的 😃
